# Generated by Django 2.1.1 on 2018-09-22 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('family_name', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
                ('passport_number', models.CharField(max_length=10)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('partner', models.ForeignKey(limit_choices_to={'profile__is_partner': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Client form',
                'verbose_name_plural': 'Client forms',
            },
        ),
        migrations.CreateModel(
            name='CreditProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_sent', models.DateTimeField(null=True)),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name=((1, 'new'), (2, 'sent'), (3, 'received'), (4, 'approved'), (5, 'declined'), (6, 'done')))),
                ('client_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.ClientForm', verbose_name='Client form')),
            ],
            options={
                'verbose_name': 'Application for a credit organization',
                'verbose_name_plural': 'Applications for a credit organizations',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('rotation_date_begin', models.DateTimeField()),
                ('rotation_date_end', models.DateTimeField()),
                ('offer_name', models.CharField(max_length=250)),
                ('offer_type', models.PositiveSmallIntegerField(default=1, verbose_name=((1, 'consumer credit'), (2, 'mortgage'), (3, 'auto credit')))),
                ('min_score', models.PositiveSmallIntegerField(default=0)),
                ('max_score', models.PositiveSmallIntegerField(default=0)),
                ('credit_organization', models.ForeignKey(limit_choices_to={'profile__is_credit_organization': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Credit organization')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_credit_organization', models.BooleanField(default=False, verbose_name='Credit organization')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Partner')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AddField(
            model_name='creditproposal',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.Offer', verbose_name='Offer'),
        ),
    ]
