# Generated by Django 2.1.1 on 2018-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditproposal',
            name='date_sent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creditproposal',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=((0, 'new'), (1, 'sent'), (2, 'received'), (3, 'approved'), (4, 'declined'), (5, 'done'))),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=((0, 'consumer credit'), (1, 'mortgage'), (2, 'auto credit'))),
        ),
    ]
